#!/bin/dash

# Do some things, than start sshd
echo "root:password" | chpasswd
mkdir -p /var/run/sshd
ln -s /opt/service/sshd /etc/service/

# Do some things, than start nginx
echo "daemon off;" >> /etc/nginx/nginx.conf
ln -s /opt/service/nginx /etc/service/

# start our post-start script
sleep 5
ln -s /opt/service/post-start /etc/service/

# Makes /etc/service/nginx/run only run once
sv once pre-start
exit 0
