#!/bin/bash

nginx () {
  /usr/bin/apt-get --yes --force-yes install nginx
  echo "daemon off;" >> /etc/nginx/nginx.conf
  mkdir /etc/service/nginx
  touch /etc/service/nginx/run
  chown root.root /etc/service/nginx/run
  chmod 756 /etc/service/nginx/run
  /bin/echo -e  '#!/bin/sh' > /etc/service/nginx/run
  /bin/echo -e  'exec /usr/sbin/nginx' >> /etc/service/nginx/run
}

sshd () {
  /usr/bin/apt-get --yes --force-yes install openssh-server
  echo "root:password" | chpasswd
  mkdir /etc/service/sshd
  touch /etc/service/sshd/run
  chown root.root /etc/service/sshd/run
  chmod 755 /etc/service/sshd/run
  /bin/echo -e '#!/bin/sh' > /etc/service/sshd/run
  /bin/echo -e 'mkdir -p /var/run/sshd' >> /etc/service/sshd/run
  /bin/echo -e 'exec /usr/sbin/sshd -D' >> /etc/service/sshd/run
}

sshd
nginx

# Makes /etc/service/nginx/run only run once
sv once run
exec /bin/true
